import { T_Task } from '@/app-types';

export const tasks: T_Task[] = [
  {
    taskId: '1',
    title: 'Fix login issue',
    label: 'Bug',
    createdAt: '2023-07-15T08:30:00Z',
    priority: 'High',
    status: 'In Progress',
    isFavorite: false,
  },
  {
    taskId: '2',
    title: 'Add search functionality',
    label: 'Feature',
    createdAt: '2023-07-20T09:45:00Z',
    priority: 'Medium',
    status: 'To Do',
    isFavorite: true,
  },
  {
    taskId: '3',
    title: 'Update API documentation',
    label: 'Documentation',
    createdAt: '2023-07-25T12:00:00Z',
    priority: 'Low',
    status: 'Done',
    isFavorite: false,
  },
  {
    taskId: '4',
    title: 'Improve performance on mobile',
    label: 'Feature',
    createdAt: '2023-07-29T14:20:00Z',
    priority: 'High',
    status: 'Backlog',
    isFavorite: false,
  },
  {
    taskId: '5',
    title: 'Fix bug in payment gateway',
    label: 'Bug',
    createdAt: '2023-08-01T10:30:00Z',
    priority: 'High',
    status: 'To Do',
    isFavorite: true,
  },
  {
    taskId: '6',
    title: 'Refactor codebase',
    label: 'Feature',
    createdAt: '2023-08-02T11:15:00Z',
    priority: 'Medium',
    status: 'In Progress',
    isFavorite: false,
  },
  {
    taskId: '7',
    title: 'Update terms of service',
    label: 'Documentation',
    createdAt: '2023-08-05T16:40:00Z',
    priority: 'Low',
    status: 'To Do',
    isFavorite: false,
  },
  {
    taskId: '8',
    title: 'Fix broken links on homepage',
    label: 'Bug',
    createdAt: '2023-08-06T07:55:00Z',
    priority: 'Medium',
    status: 'Done',
    isFavorite: true,
  },
  {
    taskId: '9',
    title: 'Add user authentication',
    label: 'Feature',
    createdAt: '2023-08-10T13:05:00Z',
    priority: 'High',
    status: 'Backlog',
    isFavorite: false,
  },
  {
    taskId: '10',
    title: 'Update privacy policy',
    label: 'Documentation',
    createdAt: '2023-08-12T08:25:00Z',
    priority: 'Low',
    status: 'In Progress',
    isFavorite: true,
  },
  {
    taskId: '11',
    title: 'Integrate third-party API',
    label: 'Feature',
    createdAt: '2023-08-15T12:40:00Z',
    priority: 'High',
    status: 'To Do',
    isFavorite: false,
  },
  {
    taskId: '12',
    title: 'Fix CSS issues on mobile',
    label: 'Bug',
    createdAt: '2023-08-17T09:10:00Z',
    priority: 'Medium',
    status: 'In Progress',
    isFavorite: true,
  },
  {
    taskId: '13',
    title: 'Review pull requests',
    label: 'Feature',
    createdAt: '2023-08-18T15:50:00Z',
    priority: 'Medium',
    status: 'To Do',
    isFavorite: false,
  },
  {
    taskId: '14',
    title: 'Write unit tests for authentication',
    label: 'Feature',
    createdAt: '2023-08-19T14:30:00Z',
    priority: 'High',
    status: 'Done',
    isFavorite: false,
  },
  {
    taskId: '15',
    title: 'Improve UI/UX for dashboard',
    label: 'Feature',
    createdAt: '2023-08-20T10:00:00Z',
    priority: 'High',
    status: 'In Progress',
    isFavorite: true,
  },
  {
    taskId: '16',
    title: 'Optimize database queries',
    label: 'Feature',
    createdAt: '2023-08-23T11:50:00Z',
    priority: 'Medium',
    status: 'Backlog',
    isFavorite: false,
  },
  {
    taskId: '17',
    title: 'Fix issue with image uploads',
    label: 'Bug',
    createdAt: '2023-08-25T08:10:00Z',
    priority: 'Medium',
    status: 'Done',
    isFavorite: true,
  },
  {
    taskId: '18',
    title: 'Write release notes for v2.1',
    label: 'Documentation',
    createdAt: '2023-08-26T16:30:00Z',
    priority: 'Low',
    status: 'To Do',
    isFavorite: false,
  },
  {
    taskId: '19',
    title: 'Add localization support',
    label: 'Feature',
    createdAt: '2023-08-30T09:00:00Z',
    priority: 'High',
    status: 'Backlog',
    isFavorite: false,
  },
  {
    taskId: '20',
    title: 'Fix issue with email notifications',
    label: 'Bug',
    createdAt: '2023-09-02T10:35:00Z',
    priority: 'High',
    status: 'To Do',
    isFavorite: true,
  },
  {
    taskId: '21',
    title: 'Update dependency versions',
    label: 'Feature',
    createdAt: '2023-09-04T08:25:00Z',
    priority: 'Low',
    status: 'In Progress',
    isFavorite: false,
  },
  {
    taskId: '22',
    title: 'Implement caching strategy',
    label: 'Feature',
    createdAt: '2023-09-06T12:20:00Z',
    priority: 'High',
    status: 'Backlog',
    isFavorite: true,
  },
  {
    taskId: '23',
    title: 'Write API tests',
    label: 'Feature',
    createdAt: '2023-09-09T14:15:00Z',
    priority: 'Medium',
    status: 'In Progress',
    isFavorite: false,
  },
  {
    taskId: '24',
    title: 'Review user feedback',
    label: 'Documentation',
    createdAt: '2023-09-12T10:45:00Z',
    priority: 'Low',
    status: 'To Do',
    isFavorite: false,
  },
  {
    taskId: '25',
    title: 'Fix error on checkout page',
    label: 'Bug',
    createdAt: '2023-09-15T17:00:00Z',
    priority: 'High',
    status: 'In Progress',
    isFavorite: true,
  },
];
