import { E_TaskStatus, T_Task } from '@/app-types';

export const tasks: T_Task[] = [
  {
  taskId: 49201,
    title: 'Fix login issue',
    type: 'Bug',
    createdAt: '2023-07-15T08:30:00Z',
    priority: 'High',
    status: E_TaskStatus.InProgress,
    isFavorite: false,
  },
  {
  taskId: 21049,
    title: 'Add search functionality',
    type: 'Feature',
    createdAt: '2023-07-20T09:45:00Z',
    priority: 'Medium',
    status: E_TaskStatus.ToDo,
    isFavorite: true,
  },
  {
  taskId: 571204,
    title: 'Update API documentation',
    type: 'Documentation',
    createdAt: '2023-07-25T12:00:00Z',
    priority: 'Low',
    status: E_TaskStatus.Done,
    isFavorite: false,
  },
  {
  taskId: 12049,
    title: 'Improve performance on mobile',
    type: 'Feature',
    createdAt: '2023-07-29T14:20:00Z',
    priority: 'High',
    status: E_TaskStatus.Backlog,
    isFavorite: false,
  },
  {
  taskId: 49215,
    title: 'Fix bug in payment gateway',
    type: 'Bug',
    createdAt: '2023-08-01T10:30:00Z',
    priority: 'High',
    status: E_TaskStatus.ToDo,
    isFavorite: true,
  },
  {
  taskId: 82041,
    title: 'Refactor codebase',
    type: 'Feature',
    createdAt: '2023-08-02T11:15:00Z',
    priority: 'Medium',
    status: E_TaskStatus.InProgress,
    isFavorite: false,
  },
  {
  taskId: 12058,
    title: 'Update terms of service',
    type: 'Documentation',
    createdAt: '2023-08-05T16:40:00Z',
    priority: 'Low',
    status: E_TaskStatus.ToDo,
    isFavorite: false,
  },
  {
  taskId: 58120,
    title: 'Fix broken links on homepage',
    type: 'Bug',
    createdAt: '2023-08-06T07:55:00Z',
    priority: 'Medium',
    status: E_TaskStatus.Done,
    isFavorite: true,
  },
  {
  taskId: 29410,
    title: 'Add user authentication',
    type: 'Feature',
    createdAt: '2023-08-10T13:05:00Z',
    priority: 'High',
    status: E_TaskStatus.Backlog,
    isFavorite: false,
  },
  {
  taskId: 71049,
    title: 'Update privacy policy',
    type: 'Documentation',
    createdAt: '2023-08-12T08:25:00Z',
    priority: 'Low',
    status: E_TaskStatus.InProgress,
    isFavorite: true,
  },
  {
  taskId: 12095,
    title: 'Integrate third-party API',
    type: 'Feature',
    createdAt: '2023-08-15T12:40:00Z',
    priority: 'High',
    status: E_TaskStatus.ToDo,
    isFavorite: false,
  },
  {
  taskId: 58124,
    title: 'Fix CSS issues on mobile',
    type: 'Bug',
    createdAt: '2023-08-17T09:10:00Z',
    priority: 'Medium',
    status: E_TaskStatus.InProgress,
    isFavorite: true,
  },
  {
  taskId: 49210,
    title: 'Review pull requests',
    type: 'Feature',
    createdAt: '2023-08-18T15:50:00Z',
    priority: 'Medium',
    status: E_TaskStatus.ToDo,
    isFavorite: false,
  },
  {
  taskId: 82049,
    title: 'Write unit tests for authentication',
    type: 'Feature',
    createdAt: '2023-08-19T14:30:00Z',
    priority: 'High',
    status: E_TaskStatus.Done,
    isFavorite: false,
  },
  {
  taskId: 12041,
    title: 'Improve UI/UX for dashboard',
    type: 'Feature',
    createdAt: '2023-08-20T10:00:00Z',
    priority: 'High',
    status: E_TaskStatus.InProgress,
    isFavorite: true,
  },
  {
  taskId: 58125,
    title: 'Optimize database queries',
    type: 'Feature',
    createdAt: '2023-08-23T11:50:00Z',
    priority: 'Medium',
    status: E_TaskStatus.Backlog,
    isFavorite: false,
  },
  {
  taskId: 49215,
    title: 'Fix issue with image uploads',
    type: 'Bug',
    createdAt: '2023-08-25T08:10:00Z',
    priority: 'Medium',
    status: E_TaskStatus.Done,
    isFavorite: true,
  },
  {
  taskId: 82015,
    title: 'Write release notes for v2.1',
    type: 'Documentation',
    createdAt: '2023-08-26T16:30:00Z',
    priority: 'Low',
    status: E_TaskStatus.ToDo,
    isFavorite: false,
  },
  {
  taskId: 12058,
    title: 'Add localization support',
    type: 'Feature',
    createdAt: '2023-08-30T09:00:00Z',
    priority: 'High',
    status: E_TaskStatus.Backlog,
    isFavorite: false,
  },
  {
  taskId: 58120,
    title: 'Fix issue with email notifications',
    type: 'Bug',
    createdAt: '2023-09-02T10:35:00Z',
    priority: 'High',
    status: E_TaskStatus.ToDo,
    isFavorite: true,
  },
  {
  taskId: 49218,
    title: 'Update dependency versions',
    type: 'Feature',
    createdAt: '2023-09-04T08:25:00Z',
    priority: 'Low',
    status: E_TaskStatus.InProgress,
    isFavorite: false,
  },
  {
  taskId: 82041,
    title: 'Implement caching strategy',
    type: 'Feature',
    createdAt: '2023-09-06T12:20:00Z',
    priority: 'High',
    status: E_TaskStatus.Backlog,
    isFavorite: true,
  },
  {
  taskId: 12095,
    title: 'Write API tests',
    type: 'Feature',
    createdAt: '2023-09-09T14:15:00Z',
    priority: 'Medium',
    status: E_TaskStatus.InProgress,
    isFavorite: false,
  },
  {
  taskId: 58124,
    title: 'Review user feedback',
    type: 'Documentation',
    createdAt: '2023-09-12T10:45:00Z',
    priority: 'Low',
    status: E_TaskStatus.ToDo,
    isFavorite: false,
  },
  {
  taskId: 49210,
    title: 'Fix error on checkout page',
    type: 'Bug',
    createdAt: '2023-09-15T17:00:00Z',
    priority: 'High',
    status: E_TaskStatus.InProgress,
    isFavorite: true,
  },
];
